export const LANDING        = '/'
export const LOGIN          = '/login'
export const SIGNUP         = '/signup'
export const RESET_PASSWORD = '/reset-pw' 
export const VERIFY_EMAIL   = '/verify'
export const PROFILE_SETUP  = '/ps'

export const DASHBOARD      = '/dashboard'
export const EXPLORE        = '/dashboard/explore'
export const GOING          = '/dashboard/going'
export const MATCHES        = '/dashboard/matches'
export const PROFILE        = '/dashboard/profile'