export const LANDING         = '/'
export const LOGIN           = '/login'
export const SIGNUP          = '/signup'
export const RESET_PASSWORD  = '/reset-pw' 
export const VERIFY_EMAIL    = '/verify'

export const PROFILE_SETUP   = '/ps'
export const PROFILE_SETUP2  = '/ps-2'
export const PROFILE_SETUP3  = '/ps-3'
export const PROFILE_SETUP4  = '/ps-4'

export const DASHBOARD       = '/dashboard'
export const EXPLORE         = '/dashboard/explore'
export const GOING           = '/dashboard/going'
export const MATCHES         = '/dashboard/matches'
export const PROFILE         = '/dashboard/profile'
export const ACHIEVEMENTS    = '/dashboard/achievements'
export const GROUP_CHAT      = '/dashboard/groupchat/:id'